version: '3.0'
services:
  cdh:
    image: cdh-oryx
    hostname: quickstart.cloudera
    ports:
      - "7180:7180"
      - "80:80"
      - "8032:8032"
     deploy:
          resources:
            limits:
              cpus: '0.50'
              memory: 16g
            reservations:
              cpus: '0.25'
              memory: 16g
#  zookeeper:
#    image: zookeeper
#    hostname: zookeeper-host
#    ports:
#      - "2181:2181"
#
#  kafka:
#    image: kafka
#    hostname: kafka-host
#    links:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#        KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-host:9092"
#        KAFKA_ZOOKEEPER_CONNECT: "zookeeper-host:2181"
#        KAFKA_BROKER_ID: 1

