version: '2.0'
services:
  cdh:
    image: cdh-oryx
    hostname: cdh-host
    ports:
      - "7180:7180"
      - "80:80"

  zookeeper:
    image: zookeeper
    hostname: zookeeper-host
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    hostname: kafka-host
    links:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
        KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-host:9092"
        KAFKA_ZOOKEEPER_CONNECT: "zookeeper-host:2181"
        KAFKA_BROKER_ID: 1

